# Generated by Django 4.2.4 on 2023-08-27 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="content",
        ),
        migrations.RemoveField(
            model_name="game",
            name="description",
        ),
        migrations.RemoveField(
            model_name="game",
            name="game",
        ),
        migrations.RemoveField(
            model_name="game",
            name="pub_date",
        ),
        migrations.RemoveField(
            model_name="game",
            name="rating",
        ),
        migrations.AddField(
            model_name="game",
            name="cover_image",
            field=models.ImageField(blank=True, null=True, upload_to="game_covers/"),
        ),
        migrations.AddField(
            model_name="game",
            name="publisher",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="developer",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="genre",
            field=models.CharField(
                choices=[
                    ("ACTION", "Action"),
                    ("RPG", "Role Playing Game"),
                    ("STRATEGY", "Strategy"),
                    ("SPORTS", "Sports"),
                    ("ADVENTURE", "Adventure"),
                    ("INDY", "Indy"),
                    ("SANDBOX", "Sandbox"),
                    ("FPS", "Shooter"),
                    ("MOBA", "MOBA"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                (
                    "pub_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date published"
                    ),
                ),
                ("featured_image", models.ImageField(upload_to="article_images/")),
                ("rating", models.DecimalField(decimal_places=1, max_digits=3)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="games.game"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Opinion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                (
                    "pub_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date published"
                    ),
                ),
                ("featured_image", models.ImageField(upload_to="article_images/")),
                ("author_opinion", models.TextField()),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="games.game"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                (
                    "pub_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date published"
                    ),
                ),
                ("featured_image", models.ImageField(upload_to="article_images/")),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="games.game"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Guide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                (
                    "pub_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date published"
                    ),
                ),
                ("featured_image", models.ImageField(upload_to="article_images/")),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="games.game"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
