# Generated by Django 4.2.4 on 2023-08-27 20:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0002_remove_game_content_remove_game_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="game",
            name="genre",
        ),
        migrations.AddField(
            model_name="game",
            name="genres",
            field=models.ManyToManyField(to="games.genre"),
        ),
    ]
