# Generated by Django 4.2.4 on 2023-08-27 22:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0003_genre_remove_game_genre_game_genres"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
