# Generated by Django 4.2.4 on 2023-08-28 01:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0006_remove_opinion_author_opinion_guide_author_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trending",
            name="title",
        ),
    ]
